[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "speech_disorders"
version = "0.1.0"
authors = [
  { name="Bastien Orset", email="bastien.orset@gmail.com" },
]
description = "A package for working with speech."
readme = "README.md"
requires-python = ">=3.7"

[project.urls]
